#!/bin/bash
set -eu

source=$(mktemp /tmp/try-black-source.XXXX)
destination=$(mktemp /tmp/try-black-destination.XXXX)

cat > $source

set +e
cat $source | black -q - > $destination
set -e

if [ $? -ne 0 ]; then
  cat $source
else
  cat $destination
fi

rm $source $destination
